### ISSUE TITLE
Typeresolvers

### ISSUE THREAD

**Issue by Domitnator** [Kentico/cloud-sample-app-vue#3]
Hi Guys,

In the Client.js I noticed that the typeresolvers are initialised:

````
let typeResolvers = [
  new TypeResolver('about_us', () => new AboutUs()),
  new TypeResolver('accessory', () => new Accessory()),
  new TypeResolver('article', () => new Article()),
  new TypeResolver('brewer', () => new Brewer()),
  new TypeResolver('cafe', () => new Cafe()),
  new TypeResolver('coffee', () => new Coffee()),
  new TypeResolver('fact_about_us', () => new FactAboutUs()),
  new TypeResolver('grinder', () => new Grinder()),
  new TypeResolver('hero_unit', () => new HeroUnit()),
  new TypeResolver('home', () => new Home()),
  new TypeResolver('hosted_video', () => new HostedVideo()),
  new TypeResolver('office', () => new Office()),
  new TypeResolver('tweet', () => new Tweet())
];
````
From the KenticoCloudDeliveryTypeScriptSDK:

![image](https://user-images.githubusercontent.com/13468638/38982307-d2a39e6a-43c1-11e8-9310-303a9d8a7fe7.png)

But, correct me if i am wrong, they are never used? Why bother configuring them? Or are they also used for parsing links in Rich text elements?

**Comment by Domitnator** [comment]
Any update on this?

**Comment by Enngage** [comment]
Hi, I'm not sure what was the state back in April (I just randomly noticed this question now), but the models are actually being used at this moment. There are not used for 'intellisense' since its javascript, but if you take a look e.g. [here ](https://github.com/Kentico/cloud-sample-app-vue/blob/master/src/Models/AboutUs.js), you will see that the models are used to 'map' properties from Kentico cloud (which often contains underscore) to more javascript friendly format (camelCase). Additionally links are being resolved as well with `resolveContentLink`. 

These type resolvers are not necessary though - you can use SDK without them. 

You can also use [model generator](https://github.com/Enngage/kentico-cloud-js/tree/master/packages/model-generator) to generate these models automatically for you.

**Comment by petrsvihlik** [comment]
Hi @Domitnator! Was your question answered satisfactorily? Can we close the issue?

**Comment by Domitnator** [comment]
Yes! Thanks for the effort! Case closed!
